# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application using Conda

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  Miniconda:
    name: Benchmark (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,spyder-ide
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: pwsh
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Conda install
        shell: pwsh
        run: |
          sudo apt-get install -y libgl1
          conda install numpy scipy meshio
          conda install pandas
          conda install bs4 lxml
          conda install pytest
          conda install gmsh
      - name: Run dynamics regression
        shell: pwsh
        run: |
          python -m pytest Tests/Regression/test_reference_frames.py
          python -m pytest Tests/Regression/test_sphere_single.py

